[package]
name = "block-stm-revm"
version = "0.1.0"
edition = "2021"

[dependencies]
dashmap = "5.5.3"
revm = "8.0.0"

[lints]
rust.missing_debug_implementations = "warn"
rust.missing_docs = "warn"
rust.unreachable_pub = "warn"

[profile.release]
debug = true
